Fix missing `import re` in `swift_debug_settings.py`
```
error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode_14.2.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/matt.robinson/Library/Developer/Xcode/DerivedData/Test-UI-Test-Target-glkvogdjirfkwghjfkgtlxpygokw/Build/Intermediates.noindex/swift_debug_settings.py", line 16, in <module>
    _TRIPLE_MATCH = re.compile(r"([^-]+-[^-]+)(-\D+)[^-]*(-.*)?")
NameError: name 're' is not defined
```