Adopt latest index-import version (v6.1.0.1) to fix issue with libzstd.1.dylib (#3174)
### Description 

Update to latest `index-import` version In order to fix [this
issue](https://github.com/MobileNativeFoundation/index-import/issues/135)
with `libzstd.1.dylib`

```
ERROR: /Users/user.name/development/iOSApp/Sources/ios/SomeDirectory/ModuleName/BUILD.bazel:7:14: Compiling Swift module //Sources/ios/SomeDirectory/ModuleName:ModuleName failed: (Exit 6): worker failed: error executing SwiftCompile command (from target //Sources/ios/SomeDirectory/ModuleName:ModuleName)
  (cd /private/var/tmp/_bazel_user.name/6a5e437287601edde41b207a856d8f03/rules_xcodeproj.noindex/build_output_base/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=18.4 \
    PATH=/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=16.3.0.16E140 \
  bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/external/rules_swift+/tools/worker/worker swiftc @bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min16.0-applebin_ios-ST-6e2671526308/bin/Sources/ios/SomeDirectory/ModuleName/ModuleName.swiftmodule-0.params)
# Configuration: b0ceba1133f56978950e06b51b3c16e1564509c2be138544537871ebbdd13844
# Execution platform: @@platforms//host:host
dyld[5952]: Library not loaded: /opt/homebrew/opt/zstd/lib/libzstd.1.dylib
  Referenced from: <9F95D36C-F1F1-3C2B-A2B2-08DD7E0943D2> /private/var/tmp/_bazel_user.name/6a5e437287601edde41b207a856d8f03/rules_xcodeproj.noindex/build_output_base/external/rules_swift++non_module_deps+build_bazel_rules_swift_index_import_6_1/index-import
  Reason: tried: '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file)
```

---------

Signed-off-by: Samuel Sainz <samuel.sainz@compass.com>