Revert "Remove `_process_user_copt` (#1560)" (#1561)
This reverts commit 166273d7add42615543b2ff3fed1d1d156dbb49b.

Errors in BwX mode:

```
error: Dependency for P1:target-MixedAnswerLib_Swift-bd8833dedbef034af8134cf809cb7f190ae462b76e22a91be694304f7bccea71-:Debug:SwiftDriver Compilation Requirements MixedAnswerLib_Swift normal arm64 com.apple.xcode.tools.swift.compiler is not absolute (bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-dbg-ST-9f9dcf014ff4/bin/iOSApp/Source/CoreUtilsMixed/MixedAnswer/MixedAnswer_objc_modulemap-module.modulemap). (in target 'MixedAnswerLib_Swift' from project 'Integration')
```