Make `rules_pkg` a non-dev dependency for now
Until I can figure out a way to not have the `load("@rules_pkg//` in build files causing loading errors like this:

> ERROR: Skipping '@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:extra_common_flags': error loading package '@rules_xcodeproj~override//xcodeproj': Unable to find package for @[unknown repo 'rules_pkg' requested from @rules_xcodeproj~override]//:mappings.bzl: The repository '@[unknown repo 'rules_pkg' requested from @rules_xcodeproj~override]' could not be resolved: No repository visible as '@rules_pkg' from repository '@rules_xcodeproj~override'.