Make the launchable target error more detailed (#2689)
If you have a non-launchable target as a launch target in the scheme,
you will get this error:
```
ERROR: Internal precondition failure:
tools/generators/legacy/src/Generator/XCSchemeInfo+LaunchActionInfo.swift:23: An XCSchemeInfo.LaunchActionInfo should have a launchable XCSchemeInfo.TargetInfo value.
```
If you have many schemes, it is difficult to find the root cause of the
problem based on the error.
These changes should simplify it.
```
ERROR: Internal precondition failure:
tools/generators/legacy/src/Generator/XCSchemeInfo+LaunchActionInfo.swift:23: An XCSchemeInfo.LaunchActionInfo should have a launchable XCSchemeInfo.TargetInfo value: <label of the target>.
```

Let me know if you see a better way to formalize the error.

---------

Signed-off-by: Vadim Smal <vadims@spotify.com>
Signed-off-by: Vadim Smal <kenshin312@gmail.com>
Co-authored-by: Vadim Smal <vadims@spotify.com>
Co-authored-by: Brentley Jones <github@brentleyjones.com>