Use full build setting path for XCBuild tracked files (#1299)
Regressed with 5aec77f2831a70164406d461811bedab7a46e6aa.

This is needed, otherwise you can get a build error like this:

> error: Build input file cannot be found:
'/Users/brentley/Developer/rules_xcodeproj/examples/integration/bazel-output-base/execroot/_rules_xcodeproj/build_output_base/execroot/\_\_main\_\_/iOSApp/Source/CoreUtilsObjC/CoreUtils/CoreUtils.pch'.
Did you forget to declare this file as an output of a script phase or
custom build rule which produces it? (in target 'FrameworkCoreUtilsObjC'
from project 'Integration')