Revert "Use the `--reuse_sandbox_directories` flag (#1784)"
This reverts commit 928cb34e819300747980396b2b617d4a15ef7a92.

Ran into errors like this:
> ERROR: /Users/brentley/Developer/rules_xcodeproj/tools/generator/BUILD:20:14: Linking tools/generator/libgenerator.library.a [for tool] failed: I/O exception during sandboxed execution: /Users/brentley/Developer/rules_xcodeproj/bazel-output-base/rules_xcodeproj/build_output_base/sandbox/darwin-sandbox/45/execroot/com_github_buildbuddy_io_rules_xcodeproj/bazel-out (No such file or directory)