Fix label creation if using bzlmod (#2249)
`cd examples/integration/` and:
```sh
bazel run --config=cache //:xcodeproj-sim_arm64
```

You'll hit this:
```sh
ERROR: Internal precondition failure:
Target @@//iOSApp/Test/SwiftUnitTests:iOSAppSwiftUnitTests was not found in the transitive dependencies of @@//:xcodeproj-sim_arm64's `top_level_targets` attribute. Did you reference an alias (only actual target labels are supported in Scheme definitions)? Check that @@//iOSApp/Test/SwiftUnitTests:iOSAppSwiftUnitTests is spelled correctly, and if it is, add it or a target that depends on it to @@//:xcodeproj-sim_arm64's `top_level_targets` attribute.
Please file a bug report at https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/new?template=bug.md
```

That's happening because constructing the `Label` directly using
`@//{}:{}` is not a good generic pattern. So changing the approach here
to normalizing the original label, get a well formed one and only then
do the replacement to use `generator_name`.

---------

Signed-off-by: Thiago Cruz <thiago.hmcruz@gmail.com>
Co-authored-by: Brentley Jones <github@brentleyjones.com>